In [3]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

In [12]:
file = pd.read_csv("/content/sample_data/mission 2.csv")

In [13]:
file.head()

   Location  Size (sqft)  Bedrooms  Bathrooms  Year Built  Condition   Price
0  Suburban         1295       5.0          1        2007          5   61023
1     Urban         1163       1.0          3        1961          1  216619
2     Urban         2020       1.0          2        1983          5  168012
3  Suburban         1279       2.0          1        2004          1  206542
4     Urban         2268       1.0          1        1961          2  316979

In [14]:
file['Location'].value_counts()

Location
Urban       342
Suburban    336
Rural       322
Name: count, dtype: int64

In [15]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Location     1000 non-null   object
 1   Size (sqft)  1000 non-null   int64
 2   Bedrooms     996 non-null    float64
 3   Bathrooms    1000 non-null   int64
 4   Year Built   1000 non-null   int64
 5   Condition    1000 non-null   int64
 6   Price        1000 non-null   int64
dtypes: float64(1), int64(5), object(1)
memory usage: 54.8+ KB

In [18]:
#filling na null values
file['Bedrooms'].fillna(file['Bedrooms'].median(), inplace=True)

<ipython-input-18-d161987277f3>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  file['Bedrooms'].fillna(file['Bedrooms'].median(), inplace=True)

In [19]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Location     1000 non-null   object
 1   Size (sqft)  1000 non-null   int64
 2   Bedrooms     1000 non-null   float64
 3   Bathrooms    1000 non-null   int64
 4   Year Built   1000 non-null   int64
 5   Condition    1000 non-null   int64
 6   Price        1000 non-null   int64
dtypes: float64(1), int64(5), object(1)
memory usage: 54.8+ KB

In [20]:
file.dropna(inplace=True)
#in case you want to delete null values

In [21]:
from sklearn.preprocessing import LabelEncoder

In [23]:
le = LabelEncoder()
file['Location'] = le.fit_transform(file['Location'])

In [24]:
file.head()

   Location  Size (sqft)  Bedrooms  Bathrooms  Year Built  Condition   Price
0         1         1295       5.0          1        2007          5   61023
1         2         1163       1.0          3        1961          1  216619
2         2         2020       1.0          2        1983          5  168012
3         1         1279       2.0          1        2004          1  206542
4         2         2268       1.0          1        1961          2  316979

In [26]:
# divide date
#x ==> features
#y  ==> target

In [29]:
x = file.drop('Price', axis=1)
x

     Location  Size (sqft)  Bedrooms  Bathrooms  Year Built  Condition
0           1         1295       5.0          1        2007          5
1           2         1163       1.0          3        1961          1
2           2         2020       1.0          2        1983          5
3           1         1279       2.0          1        2004          1
4           2         2268       1.0          1        1961          2
..        ...          ...       ...        ...         ...        ...
995         2         3273       4.0          2        1968          1
996         0         3180       3.0          3        2010          2
997         0         3342       3.0          1        1997          4
998         1         1806       4.0          2        1982          1
999         0          918       3.0          2        2003          1

[1000 rows x 6 columns]

In [30]:
y = file['Price']

In [31]:
y

0       61023
1      216619
2      168012
3      206542
4      316979
        ...
995    340160
996    345451
997    284286
998    212993
999    136188
Name: Price, Length: 1000, dtype: int64

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [33]:
dt = DecisionTreeRegressor()
dt.fit(x_train, y_train)

DecisionTreeRegressor()

In [34]:
y_pred = dt.predict(x_test)

In [37]:
#accuracy ==> classifciation
#r2_score ==> regreesion
from sklearn.metrics import r2_score
print(r2_score(y_pred, y_test) * 100, '%')

100.0 %